// <auto-generated />
using System;
using IntegrationImport.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IntegrationImport.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428084808_InitialHrmsSyncSchema")]
    partial class InitialHrmsSyncSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IntegrationImport.Domain.Entities.ImportRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("CreatedByClientId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_client_id");

                    b.Property<DateOnly>("EffectiveDate")
                        .HasColumnType("date")
                        .HasColumnName("effective_date");

                    b.Property<int>("EntityType")
                        .HasColumnType("integer")
                        .HasColumnName("entity_type");

                    b.Property<int>("ItemCount")
                        .HasColumnType("integer")
                        .HasColumnName("item_count");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at_utc");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference_id");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_import_requests");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_import_requests_reference_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_import_requests_status");

                    b.HasIndex("ReferenceId", "EntityType")
                        .IsUnique()
                        .HasDatabaseName("ix_import_requests_reference_id_entity_type");

                    b.ToTable("ImportRequests", (string)null);
                });

            modelBuilder.Entity("IntegrationImport.Domain.Entities.OrganizationUnit.OrganizationUnitImportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("text")
                        .HasColumnName("changed_fields_json");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("HrmsId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hrms_id");

                    b.Property<Guid>("ImportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_request_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParentHrmsId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("parent_hrms_id");

                    b.HasKey("Id")
                        .HasName("pk_organization_unit_import_items");

                    b.HasIndex("HrmsId")
                        .HasDatabaseName("ix_organization_unit_import_items_hrms_id");

                    b.HasIndex("ImportRequestId")
                        .HasDatabaseName("ix_organization_unit_import_items_import_request_id");

                    b.HasIndex("ImportRequestId", "HrmsId")
                        .HasDatabaseName("ix_organization_unit_import_items_import_request_id_hrms_id");

                    b.ToTable("OrganizationUnitImportItems", (string)null);
                });

            modelBuilder.Entity("IntegrationImport.Domain.Entities.User.ImportedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("KeycloakUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_user_id");

                    b.Property<string>("LastAction")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_action");

                    b.Property<Guid?>("LastImportItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_import_item_id");

                    b.Property<Guid?>("LastImportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_import_request_id");

                    b.Property<string>("LastName")
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("LastSyncStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_sync_status");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at_utc");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("SourceImportItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_import_item_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_imported_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_users_external_id");

                    b.HasIndex("KeycloakUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_users_keycloak_user_id")
                        .HasFilter("\"keycloak_user_id\" IS NOT NULL");

                    b.HasIndex("SourceImportItemId")
                        .IsUnique()
                        .HasDatabaseName("ix_imported_users_source_import_item_id")
                        .HasFilter("\"source_import_item_id\" IS NOT NULL");

                    b.HasIndex("Username")
                        .HasDatabaseName("ix_imported_users_username");

                    b.ToTable("ImportedUsers", (string)null);
                });

            modelBuilder.Entity("IntegrationImport.Domain.Entities.User.UserImportItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime?>("AppliedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("applied_at_utc");

                    b.Property<string>("ApplyError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("apply_error");

                    b.Property<string>("ChangedFieldsJson")
                        .HasColumnType("text")
                        .HasColumnName("changed_fields_json");

                    b.Property<int>("DispatchAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("dispatch_attempts");

                    b.Property<DateTime?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("dispatched_at_utc");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool?>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("first_name");

                    b.Property<string>("HrmsId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hrms_id");

                    b.Property<Guid>("ImportRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("import_request_id");

                    b.Property<string>("LastDispatchError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_dispatch_error");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("last_name");

                    b.Property<string>("OrgUnitHrmsIdsJson")
                        .HasColumnType("text")
                        .HasColumnName("org_unit_hrms_ids_json");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("phone_number");

                    b.Property<string>("ProcessStatus")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("process_status");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_notes");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("review_status");

                    b.Property<DateTime?>("ReviewedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at_utc");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Username")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.Property<string>("VatId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vat_id");

                    b.HasKey("Id")
                        .HasName("pk_user_import_items");

                    b.HasIndex("HrmsId")
                        .HasDatabaseName("ix_user_import_items_hrms_id");

                    b.HasIndex("ImportRequestId")
                        .HasDatabaseName("ix_user_import_items_import_request_id");

                    b.HasIndex("ImportRequestId", "HrmsId")
                        .HasDatabaseName("ix_user_import_items_import_request_id_hrms_id");

                    b.HasIndex("ReviewStatus", "ProcessStatus", "DispatchedAtUtc")
                        .HasDatabaseName("ix_user_import_items_review_status_process_status_dispatched_at_");

                    b.ToTable("UserImportItems", (string)null);
                });

            modelBuilder.Entity("IntegrationImport.Domain.Entities.OrganizationUnit.OrganizationUnitImportItem", b =>
                {
                    b.HasOne("IntegrationImport.Domain.Entities.ImportRequest", "ImportRequest")
                        .WithMany("OrganizationUnits")
                        .HasForeignKey("ImportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_organization_unit_import_items_import_requests_import_request_id");

                    b.Navigation("ImportRequest");
                });

            modelBuilder.Entity("IntegrationImport.Domain.Entities.User.UserImportItem", b =>
                {
                    b.HasOne("IntegrationImport.Domain.Entities.ImportRequest", "ImportRequest")
                        .WithMany("Users")
                        .HasForeignKey("ImportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_import_items_import_requests_import_request_id");

                    b.Navigation("ImportRequest");
                });

            modelBuilder.Entity("IntegrationImport.Domain.Entities.ImportRequest", b =>
                {
                    b.Navigation("OrganizationUnits");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
